# config server
config: 
  uri: "http://localhost:8888"

# eureka client 
eureka:
  client:
    uri: "http://localhost:8761/eureka"

# test
message: "Voici mon message"

# project database connection
project: 
  datasource:
    url: jdbc:mysql://localhost:3306/invest_gate_projects
    username: root
    password: ""

# admin database connection
admin: 
  datasource:
    url: jdbc:mysql://localhost:3306/invest_gate_admins
    username: root
    password: ""

# investor database connection
investor: 
  datasource:
    url: jdbc:mysql://localhost:3306/invest_gate_investors
    username: root
    password: ""

# student database connection
student: 
  datasource:
    url: jdbc:mysql://localhost:3306/invest_gate_students
    username: root
    password: ""

# config email 
mail:
  username: yasaiteams002@gmail.com
  password: tjtdrvdfzqxghmkv
   


