# config server
config: 
  uri: "http://localhost:8888"

# eureka client 
eureka:
  client:
    uri: "http://localhost:8761/eureka"

# test
message: "Voici mon message"

# project database connection
project: 
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: postgresql

# investor database connection
investor: 
  datasource:
    url: jdbc:mysql://localhost:3306/investor
    username: root
    password: ""
